apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: oci
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/stefanprodan/manifests/podinfo
  ref:
    tag: "6.3.0"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: oci
  namespace: oci
spec:
  targetNamespace: default
  interval: 10m
  path: "./"
  prune: true
  sourceRef:
    kind: OCIRepository
    name: oci
  wait: true
  timeout: 2m
