apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: main
    tag: "6.3.0"
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: podinfo
  path: ./apps/podinfo
  prune: true
  wait: true
  timeout: 2m